remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [HackUPC24 - Join&Eat]
description: [Join&Eat team's submission to HackUPC24]
markdown: GFM
